"""weather

Revision ID: 5be1268ba3b3
Revises: e9dc1621a797
Create Date: 2020-04-12 07:54:42.632278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be1268ba3b3'
down_revision = 'e9dc1621a797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('high', sa.FLOAT(), nullable=True))
    op.add_column('weather', sa.Column('low', sa.FLOAT(), nullable=True))
    op.drop_column('weather', 'temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('temp', sa.DECIMAL(), nullable=True))
    op.drop_column('weather', 'low')
    op.drop_column('weather', 'high')
    # ### end Alembic commands ###
