"""ObjectOfInterest

Revision ID: e9dc1621a797
Revises: 64e5a16f708d
Create Date: 2020-03-23 22:20:03.321190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dc1621a797'
down_revision = '64e5a16f708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_stored', sa.DateTime(), nullable=True),
    sa.Column('vis_start', sa.DateTime(), nullable=True),
    sa.Column('vis_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_of_interest_date_stored'), 'object_of_interest', ['date_stored'], unique=False)
    op.create_index(op.f('ix_object_of_interest_vis_end'), 'object_of_interest', ['vis_end'], unique=False)
    op.create_index(op.f('ix_object_of_interest_vis_start'), 'object_of_interest', ['vis_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_of_interest_vis_start'), table_name='object_of_interest')
    op.drop_index(op.f('ix_object_of_interest_vis_end'), table_name='object_of_interest')
    op.drop_index(op.f('ix_object_of_interest_date_stored'), table_name='object_of_interest')
    op.drop_table('object_of_interest')
    # ### end Alembic commands ###
